controllers/CondoController.php
<?
namespace app\controllers;

use app\components\alertComponent;
use app\models\AdmModel;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\CondominioModel;
use app\models\ConselhoModel;
use app\components\mascaraComponent;
use Yii;

class CondoController extends Controller{
    #funcao para listar condominios
    public function actionListCondominio(){

        #verifica o login
        if(yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        #atribui a tabela condominios na var
        $condoTable = CondominioModel::tableName();
        #atribui a tabela admins na var
        $admTable = AdmModel::tableName();

        #realiza a query de busca de dados no BD
        $query = (new \yii\db\Query())
        ->select(
            'condo.id,
            adm.nome_adm as from_adm,
            condo.nomeCondo,
            condo.qtBloco,
            condo.cep,
            condo.logradouro,
            condo.numero,
            condo.bairro,
            condo.cidade,
            condo.estado,
            condo.dataCadastro'
        )
        ->from($condoTable.' condo')
        #faz o inner join da tabela admins para buscar a relacao
        ->innerJoin($admTable.' adm','adm.id = condo.from_adm');

        #paginacao com 6 itens
        $paginacao = new Pagination([
            'defaultPageSize' => 6,
            'totalCount' => $query->count(),
        ]);

        #ordena a lista por id
        $condo = $query->orderBy('id')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();
        
        #renderiza a listagem
        return $this->render('list-condominio', [
            'condominios' => $condo,
            'paginacao' => $paginacao,
        ]);
    }

    #funcao para renderizar o cadastro
    public function actionCondominio(){

        #verifica o login
        if(yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        
        return $this->render('condominio');
    }

    #funcao para realizar o cadastro
    public function actionRealizaCadastroCondo(){
        $request = \yii::$app->request;

        #se request for post, atribui os dados do post na model e salva
        if($request->isPost){
            $model = new CondominioModel();
            #tira a mascara do cep no banco de dados
            foreach($request->post() as $field=>$value){
                if($field == 'cep'){
                    $getMani[$field] = mascaraComponent::unmask($value);
                }
                else{
                    $getMani[$field] = $value;
                }
            }
            $model->attributes = $getMani;
            $model->save();
            return $this->redirect(['condo/list-condominio']);
        }

        return $this->render('condominio');
    }

    #funcao para listar os condominios em outros cadastros
    public static function listCondoSelect(){
        $query = CondominioModel::find();
        return $query->orderBy('id')->all();
    }

    #funcao para renderizar a edicao
    public function actionEditaCondominio(){
        
        #esconde o layout
        $this->layout = false;

        $request = \yii::$app->request;

        #se request for get, busca o condominio pelo id do get
        if($request->isGet){
            $query = CondominioModel::find();
            $condos = $query->where(['id' => $request->get()])->one();
        }
        #renderiza a edicao
        return $this->render('edita-condominio',[
            'edit' => $condos
        ]);
    }

    #funcao para salvar os dados editados
    public function actionEditaCadastroCondo(){

        $request = \yii::$app->request;

        #se request for post, busca o condominio pelo id e atribui os dados do post nele
        if($request->isPost){

            $model = CondominioModel::findOne($request->post('id'));
            $model->attributes = $request->post();

            #se os dados baterem com o BD, atualiza
            if($model->update()){
                return $this->redirect(['condo/list-condominio']);
            }
            #se nao, exiba erro
            else{
                return $this->redirect(['condo/list-condominio', 'msg' => 'erro']);
            }
        }
    }

    #funcao para deletar condominio
    public function actionDeletaCondo(){
        $request = \yii::$app->request;

        #se request for get, pega o id do condominio no get
        if($request->isGet){
            $model = CondominioModel::findOne($request->get('id'));
            #se pegou o id, deleta
            if($model->delete()){
                return $this->redirect(['condo/list-condominio', 'myAlert' => ['type' => 'success', 'msg' => 'Registro deletado']]);
            }
            #se nao, exiba erro
            else{
                return $this->redirect(['condo/list-condominio', 'myAlert' => ['type' => 'danger', 'msg' => 'Registro não deletado']]);
            }
        }
    }

    #funcao para retornar o total de condominios cadastrados
    public static function TotalCondos(){
        $qry = yii::$app->db->createCommand(
            'SELECT COUNT(id) FROM condominio'
        )->queryScalar();
        return $qry;
    }

    #funcao para retornar o nome dos condominios
    public static function NomesCondos(){
        $qry = yii::$app->db->createCommand(
            'SELECT nomeCondo FROM condominio'
        )->queryAll();
        return $qry;
    }
}
?>

views/condo/condominio.php
<?
use yii\helpers\Url;
use app\controllers\AdmController;
use app\components\estadosComponent;
?>

<center class="mt-4 pb-4">
    <h1 class="col-12">Cadastro de Condomínio</h1>
</center>
    <form action="<?echo Url::to(['condo/realiza-cadastro-condo']);?>" method="POST" class="formCondo">
        <div class="row">
            <div class="col-12 col-md-4 mb-3">
                <select name="from_adm" class="custom-select" required>
                    <option value="">Selecione a admin...</option>
                    <?
                    foreach(AdmController::listAdminSelect() as $adm){
                    ?>
                    <option value="<?=$adm['id']?>"><?=$adm['nome_adm']?></option>
                    <?}?>
                </select>
            </div>
            <div class="col-12 col-md-4 mb-3">
                <input type="text" class="form-control" name="qtBloco" value="" required placeholder="Blocos">
            </div>
            <div class="col-12 col-md-4 mb-3">
                <input type="text" class="form-control" name="nomeCondo" value="" required placeholder="Nome">
            </div>
            <div class="col-12 col-md-4 mb-3">
                <input type="text" class="form-control" name="logradouro" value="" required placeholder="Logradouro">
            </div>
            <div class="col-12 col-md-4 mb-3">
                <input type="text" class="form-control" name="numero" value="" required placeholder="N°">
            </div>
            <div class="col-12 col-md-4 mb-3">
                <input type="text" class="form-control" name="bairro" value="" required placeholder="Bairro">
            </div>
            <div class="col-12 col-md-4 mb-3">
                <input type="text" class="form-control" name="cidade" value="" required placeholder="Cidade">
            </div>
            <div class="col-12 col-md-4 mb-3">
                <select name="estado" class="custom-select" required>
                    <option value="">Selecione um estado...</option>
                    <?
                    foreach(estadosComponent::estados() as $sig=>$uf){
                    ?>
                    <option value="<?=$sig?>"><?=$uf?></option>
                    <?}?>
                </select>
            </div>
            <div class="col-12 col-md-4">
                <input type="text" class="form-control cep" name="cep" value="" required placeholder="CEP">
            </div>
            

            <input type="hidden" name="<?= \yii::$app->request->csrfParam;?>" value="<?= \yii::$app->request->csrfToken;?>">

            <div class="col-12 col-md-12 mt-3">
                <center>
                    <button class="btn btn-info col-6" type="submit">Enviar</button>
                </center>
            </div>
        </div>
    </form>

views/condo/edita-condominio.php
<?
use yii\helpers\Url;
use app\controllers\AdmController;
use app\components\estadosComponent;
use app\components\selectedComponent;
use app\components\mascaraComponent;
?>

<center class="mt-4 pb-4">
    <h1 class="col-12">Edição de Condomínio</h1>
</center>
    <form action="<?echo Url::to(['condo/edita-cadastro-condo']);?>" method="POST" class="formCondo">
        <div class="row">
            <div class="col-12 col-md-4 mb-3">
                <select name="from_adm" class="custom-select" required>
                    <option value="">Selecione a admin...</option>
                    <?
                    foreach(AdmController::listAdminSelect() as $adm){
                    ?>
                    <option value="<?=$adm['id']?>"<?=selectedComponent::isSelected($adm['id'], $edit['from_adm'])?>><?=$adm['nome_adm']?></option>
                    <?}?>
                </select>
            </div>
            <div class="col-12 col-md-4 mb-3">
                <input type="text" class="form-control" name="qtBloco" value="<?=$edit['qtBloco']?>" required placeholder="Blocos">
            </div>
            <div class="col-12 col-md-4 mb-3">
                <input type="text" class="form-control" name="nomeCondo" value="<?=$edit['nomeCondo']?>" required placeholder="Nome">
            </div>
            <div class="col-12 col-md-4 mb-3">
                <input type="text" class="form-control" name="logradouro" value="<?=$edit['logradouro']?>" required placeholder="Logradouro">
            </div>
            <div class="col-12 col-md-4 mb-3">
                <input type="text" class="form-control" name="numero" value="<?=$edit['numero']?>" required placeholder="N°">
            </div>
            <div class="col-12 col-md-4 mb-3">
                <input type="text" class="form-control" name="bairro" value="<?=$edit['bairro']?>" required placeholder="Bairro">
            </div>
            <div class="col-12 col-md-4 mb-3">
                <input type="text" class="form-control" name="cidade" value="<?=$edit['cidade']?>" required placeholder="Cidade">
            </div>
            <div class="col-12 col-md-4 mb-3">
                <select name="estado" class="custom-select" required>
                    <option value="">Selecione um estado...</option>
                    <?
                    foreach(estadosComponent::estados() as $sig=>$uf){
                    ?>
                    <option value="<?=$sig?>"<?=selectedComponent::isSelected($sig, $edit['estado'])?>><?=$uf?></option>
                    <?}?>
                </select>
            </div>
            <div class="col-12 col-md-4">
                <input type="text" class="form-control cep" name="cep" value="<?=mascaraComponent::mascara($edit['cep'],'cep')?>" required placeholder="CEP">
            </div>
            

            <input type="hidden" name="<?= \yii::$app->request->csrfParam;?>" value="<?= \yii::$app->request->csrfToken;?>">

            <input type="hidden" name="id" value="<?=$edit['id']?>">

            <div class="col-12 col-md-12 mt-3">
                <center>
                    <button class="btn btn-info col-6 mb-2" type="submit">Salvar</button>
                </center>
            </div>
        </div>
    </form>

views/condo/list-condominio.php
<?

use app\components\alertComponent;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;
use app\components\mascaraComponent;
use app\components\modalComponent;

$url_site = Url::base(true);

if(isset($_GET['myAlert'])){
    echo alertComponent::myAlert($_GET['myAlert']['type'],$_GET['myAlert']['msg']);
}

?>


<center class="mt-4 pb-4">
    <h1 class="col-12">Condomínios</h1>
</center>
<div class="row">
    <div class="col-12">
        <div class="table-responsive">
            <table class="table mt-3" id="listaCondominios">
                <thead class="thead-dark">
                    <tr>
                    <th scope="col">Blocos</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Logradouro</th>
                    <th scope="col">N°</th>
                    <th scope="col">Bairro</th>
                    <th scope="col">Cidade</th>
                    <th scope="col">Estado</th>
                    <th scope="col">CEP</th>
                    <th scope="col">Admin</th>
                    <th scope="col">DT. Cadastro</th>
                    <th align="center"><a href="index.php?r=condo%2Fcondominio" class="btn btn-info btn-sm">ADICIONAR</a></th>
                    </tr>
                </thead>
                <tbody>
                    <? 

                    foreach($condominios as $dados){
                        
                    ?>
                    <tr data-id="<?=$dados['id']?>">
                    <td><?=$dados['qtBloco']?></td>
                    <td><?=$dados['nomeCondo']?></td>
                    <td><?=$dados['logradouro']?></td>
                    <td><?=$dados['numero']?></td>
                    <td><?=$dados['bairro']?></td>
                    <td><?=$dados['cidade']?></td>
                    <td><?=$dados['estado']?></td>
                    <td><?=mascaraComponent::mascara($dados['cep'],'cep')?></td>
                    <td><?=$dados['from_adm']?></td>
                    <td><?=Yii::$app->formatter->format($dados['dataCadastro'],'date')?></td>
                    <td>
                        <a style="padding-right: 25px;" href="<?=$url_site?>/index.php?r=condo/deleta-condo&id=<?=$dados['id']?>" class="removerCondominio"><i class="icofont-ui-delete botao"></i></a>
                        <a class="openModal" href="<?=$url_site?>/index.php?r=condo/edita-condominio&id=<?=$dados['id']?>"><i class="icofont-edit botao"></i></a>
                    </td>
                    </tr>
                    <?}?>
                    <tr>
                    <td colspan="3">&nbsp;</td>
                    <td colspan="3">&nbsp;</td>
                    <td colspan="3">&nbsp;</td>
                    <td colspan="1">&nbsp;</td>
                    <td colspan="2" align="right" class="totalRegistros">Total Registros: <?=$paginacao->totalCount?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row">
    <?= LinkPager::widget(
        [
            'pagination' => $paginacao,
            'linkContainerOptions' => [
                'class' => 'page-item'
            ],
            'linkOptions' => [
                'class' => 'page-link'
            ],
            'disabledListItemSubTagOptions' => [
                'class' => 'page-link'
            ]
        ]
    ) ?>
</div>
<?=modalComponent::initModal();?>