controllers/ConselhoController.php
<?
namespace app\controllers;

use app\models\CondominioModel;
use yii\web\Controller;
use yii\data\Pagination;
use app\models\ConselhoModel;
use Yii;

class ConselhoController extends Controller{
    #funcao para listar o conselho
    public function actionListSindico(){

        #verifica o login
        if(yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        #atribui a tabela conselho na var
        $consTable = ConselhoModel::tableName();
        #atribui a tabela condominio na var
        $condoTable = CondominioModel::tableName();

        #realiza a consulta no BD
        $query = (new \yii\db\Query())
        ->select(
            'cons.id,
            condo.nomeCondo as condoSindico,
            cons.sindico,
            cons.subSindico,
            cons.conselheiro,
            cons.dataCadastro'
        )
        ->from($consTable.' cons')
        ->innerJoin($condoTable.' condo','condo.id = cons.condoSindico');

        #paginacao com 6 itens
        $paginacao = new Pagination([
            'defaultPageSize' => 6,
            'totalCount' => $query->count(),
        ]);

        #ordena a lista por id
        $cons = $query->orderBy('id')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();
        
        #renderiza a listagem
        return $this->render('list-sindico', [
            'sindicos' => $cons,
            'paginacao' => $paginacao,
        ]);
    }

    #funcao para renderizar o cadastro do conselho
    public function actionSindico(){

        #verifica o login
        if(yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        return $this->render('sindico');
    }

    #funcao para realizar o cadastro de conselho
    public function actionRealizaCadastroConselho(){
        $request = \yii::$app->request;

        #se request for post, atribui os dados do post na model e salva os dados
        if($request->isPost){
            $model = new ConselhoModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['conselho/list-sindico']);
        }

        return $this->render('sindico');
    }

    #funcao para abrir a edicao de conselho
    public function actionEditaConselho(){
        #esconde o layout
        $this->layout = false;
        $request = \yii::$app->request;

        #se request for get, busca o conselho pelo id selecionado no get
        if($request->isGet){
            $query = ConselhoModel::find();
            $cons = $query->where(['id' => $request->get()])->one();
        }

        #renderiza a edicao
        return $this->render('edita-conselho',[
            'edit' => $cons
        ]);
    }

    #funcao para salvar a edicao de conselho
    public function actionEditaCadastroConselho(){

        $request = \yii::$app->request;

        #se request for post, pega o id no post e atribui os dados na model
        if($request->isPost){

            $model = ConselhoModel::findOne($request->post('id'));
            $model->attributes = $request->post();

            #se os dados baterem com o BD, atualiza
            if($model->update()){
                return $this->redirect(['conselho/list-sindico']);
            }
            #se nao, exiba erro
            else{
                return $this->redirect(['conselho/list-sindico', 'msg' => 'erro']);
            }
        }
    }

    #funcao para deletar o conselho
    public function actionDeletaConselho(){
        $request = \yii::$app->request;

        #se request for get, pega o id selecionado no get
        if($request->isGet){
            $model = ConselhoModel::findOne($request->get('id'));
            #se pegou o id, deleta o conselho
            if($model->delete()){
                return $this->redirect(['conselho/list-sindico', 'myAlert' => ['type' => 'success', 'msg' => 'Registro deletado']]);
            }
            #se nao, exiba erro
            else{
                return $this->redirect(['conselho/list-sindico', 'myAlert' => ['type' => 'danger', 'msg' => 'Registro não deletado']]);
            }
        }
    }
}
?>

views/conselho/edita-conselho.php
<?

use app\components\selectedComponent;
use yii\helpers\Url;
use app\controllers\CondoController;
?>

<center class="mt-4 pb-4">
    <h1 class="col-12">Edição de Conselho</h1>
</center>
    <form action="<?echo Url::to(['conselho/edita-cadastro-conselho']);?>" method="POST" class="formConselho">
        <div class="row">
            <div class="col-12 col-md-3 mb-3">
                <select name="condoSindico" class="custom-select" required>
                    <option value="">Selecione o condomínio...</option>
                    <?
                    foreach(CondoController::listCondoSelect() as $condo){
                    ?>
                    <option value="<?=$condo['id']?>"<?=selectedComponent::isSelected($condo['id'], $edit['condoSindico'])?>><?=$condo['nomeCondo']?></option>
                    <?}?>
                </select>
            </div>
            <div class="col-12 col-md-3 mb-3">
                <input type="text" class="form-control" name="sindico" value="<?=$edit['sindico']?>" required placeholder="Síndico">
            </div>
            <div class="col-12 col-md-3 mb-3">
                <input type="text" class="form-control" name="subSindico" value="<?=$edit['subSindico']?>" required placeholder="Sub Síndico">
            </div>
            <div class="col-12 col-md-3 mb-3">
                <input type="text" class="form-control" name="conselheiro" value="<?=$edit['conselheiro']?>" required placeholder="Conselheiro">
            </div>
            

            <input type="hidden" name="<?= \yii::$app->request->csrfParam;?>" value="<?= \yii::$app->request->csrfToken;?>">

            <input type="hidden" name="id" value="<?=$edit['id']?>">

            <div class="col-12 col-md-12 mt-3">
                <center>
                    <button class="btn btn-info col-6 mb-2" type="submit">Salvar</button>
                </center>
            </div>
        </div>
    </form>

views/conselho/list-sindico.php
<?

use app\components\modalComponent;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;
use app\components\alertComponent;

$url_site = Url::base(true);

if(isset($_GET['myAlert'])){
    echo alertComponent::myAlert($_GET['myAlert']['type'],$_GET['myAlert']['msg']);
}

?>

<center>
<h1>Conselhos</h1>
</center>
<div class="row">
    <div class="col-12">
        <div class="table-responsive">
            <table class="table mt-3" id="listaSindicos">
                <thead class="thead-dark">
                    <tr>
                    <th scope="col">Síndico</th>
                    <th scope="col">Sub Síndico</th>
                    <th scope="col">Conselheiro</th>
                    <th scope="col">Condomínio</th>
                    <th scope="col">DT. Cadastro</th>
                    <th align="center"><a href="index.php?r=conselho%2Fsindico" class="btn btn-info btn-sm">ADICIONAR</a></th>
                    </tr>
                </thead>
                <tbody>
                    <? 

                    foreach($sindicos as $dados){
                        
                    ?>
                    <tr data-id="<?=$dados['id']?>">
                    <td><?=$dados['sindico']?></td>
                    <td><?=$dados['subSindico']?></td>
                    <td><?=$dados['conselheiro']?></td>
                    <td><?=$dados['condoSindico']?></td>
                    <td><?=Yii::$app->formatter->format($dados['dataCadastro'],'date')?></td>
                    <td>
                        <a style="padding-right: 25px;" href="<?=$url_site?>/index.php?r=conselho/deleta-conselho&id=<?=$dados['id']?>" class="removerSindico"><i class="icofont-ui-delete botao"></i></a>
                        <a class="openModal" href="<?=$url_site?>/index.php?r=conselho/edita-conselho&id=<?=$dados['id']?>"><i class="icofont-edit botao"></i></a>
                    </td>
                    </tr>
                    <?}?>
                    <tr>
                    <td colspan="3">&nbsp;</td>
                    <td colspan="1">&nbsp;</td>
                    <td colspan="2" align="right" class="totalRegistros">Total Registros: <?=$paginacao->totalCount?></td>
                    </tr>
                </tbody>
            </table>
        </div>    
    </div>
</div>
<div class="row">
    <?= LinkPager::widget(
        [
            'pagination' => $paginacao,
            'linkContainerOptions' => [
                'class' => 'page-item'
            ],
            'linkOptions' => [
                'class' => 'page-link'
            ],
            'disabledListItemSubTagOptions' => [
                'class' => 'page-link'
            ]
        ]
    ) ?>
</div>
<?=modalComponent::initModal();?>

views/conselho/sindico.php
<?
use yii\helpers\Url;
use app\controllers\CondoController;
?>

<center class="mt-4 pb-4">
    <h1 class="col-12">Cadastro de Conselho</h1>
</center>
    <form action="<?echo Url::to(['conselho/realiza-cadastro-conselho']);?>" method="POST" class="formConselho">
        <div class="row">
            <div class="col-12 col-md-3 mb-3">
                <select name="condoSindico" class="custom-select" required>
                    <option value="">Selecione o condomínio...</option>
                    <?
                    foreach(CondoController::listCondoSelect() as $condo){
                    ?>
                    <option value="<?=$condo['id']?>"><?=$condo['nomeCondo']?></option>
                    <?}?>
                </select>
            </div>
            <div class="col-12 col-md-3 mb-3">
                <input type="text" class="form-control" name="sindico" value="" required placeholder="Síndico">
            </div>
            <div class="col-12 col-md-3 mb-3">
                <input type="text" class="form-control" name="subSindico" value="" required placeholder="Sub Síndico">
            </div>
            <div class="col-12 col-md-3 mb-3">
                <input type="text" class="form-control" name="conselheiro" value="" required placeholder="Conselheiro">
            </div>
            

            <input type="hidden" name="<?= \yii::$app->request->csrfParam;?>" value="<?= \yii::$app->request->csrfToken;?>">

            <div class="col-12 col-md-12 mt-3">
                <center>
                    <button class="btn btn-info col-6" type="submit">Enviar</button>
                </center>
            </div>
        </div>
    </form>