controllers/AdmController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\AdmModel;
use app\components\alertComponent;
use app\components\mascaraComponent;
use Yii;

class AdmController extends Controller{
    #funcao para listar admins
    public function actionListAdmin(){
        #verifica se o usuario está logado
        if(yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        #busca as admins no BD
        $query = AdmModel::find();

        #paginacao com 6 itens
        $paginacao = new Pagination([
            'defaultPageSize' => 6,
            'totalCount' => $query->count(),
        ]);

        #ordena a lista pelo id
        $adm = $query->orderBy('id')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();
        
        #renderiza a listagem
        return $this->render('list-admin', [
            'administradoras' => $adm,
            'paginacao' => $paginacao,
        ]);
    }

    #funcao para renderizar o cadastro de admin
    public function actionAdmin(){

        #verifica se está logado
        if(yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        
        return $this->render('admin');
    }

    public function actionRealizaCadastroAdmin(){
        $request = \yii::$app->request;

        #se request for post, busca os atributos da model e salva os dados
        if($request->isPost){
            $model = new AdmModel();
            #tira a mascara do cnpj no banco
            foreach($request->post() as $field=>$value){
                if($field == 'cnpj'){
                    $getMani[$field] = mascaraComponent::unmask($value);
                }
                else{
                    $getMani[$field] = $value;
                }
            }
            $model->attributes = $getMani;
            $model->save();
            return $this->redirect(['adm/list-admin']);
        }

        return $this->render('admin');
    }

    #funcao para listar as admins existentes em outras telas de cadastro
    public static function listAdminSelect(){
        $query = AdmModel::find();
        return $query->orderBy('id')->all();
    }

    #funcao para abrir a edicao da admin
    public function actionEditaAdmin(){
        #esconde o layout da edicao
        $this->layout = false;

        $request = \yii::$app->request;

        #se request for get, busca as adms e filtra pelo id selecionado no get
        if($request->isGet){
            $query = AdmModel::find();
            $adms = $query->where(['id' => $request->get()])->one();
        }
        #renderiza a tela de edicao da admin
        return $this->render('edita-admin',[
            'edit' => $adms
        ]);
    }

    #funcao para salvar os dados editados da admin
    public function actionEditaCadastroAdmin(){

        $request = \yii::$app->request;

        #se request for post, busca uma admin pelo id, e coloca os atributos do request na model
        if($request->isPost){

            $model = AdmModel::findOne($request->post('id'));
            $model->attributes = $request->post();

            #se os dados baterem com as tabelas do BD, atualiza a admin e redireciona para a listagem
            if($model->update()){
                return $this->redirect(['adm/list-admin']);
            }
            #se nao, exiba erro
            else{
                return $this->redirect(['adm/list-admin', 'msg' => 'erro']);
            }
        }
    }

    #funcao para deletar a admin
    public function actionDeletaAdmin(){
        $request = \yii::$app->request;

        #se request for get, pega o id da admin no get
        if($request->isGet){
            $model = AdmModel::findOne($request->get('id'));

            #se pegou o id, deleta a admin
            if($model->delete()){
                return $this->redirect(['adm/list-admin', 'myAlert' => ['type' => 'success', 'msg' => 'Registro deletado']]);
            }
            #se nao, exiba erro
            else{
                return $this->redirect(['adm/list-admin', 'myAlert' => ['type' => 'danger', 'msg' => 'Registro não deletado']]);
            }
        }
    }

    #funcao para retornar o total de administradoras cadastradas
    public static function TotalAdmins(){
        $qry = yii::$app->db->createCommand(
            'SELECT COUNT(id) FROM administradoras'
        )->queryScalar();
        return $qry;
    }

    #funcao para retornar o nome dos administradoras
    public static function NomesAdmins(){
        $qry = yii::$app->db->createCommand(
            'SELECT nome_adm FROM administradoras'
        )->queryAll();
        return $qry;
    }
}
?>

controllers/BlocoController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\BlocoModel;
use app\models\CondominioModel;
use Yii;

class BlocoController extends Controller{
    #funcao para listar os blocos
    public function actionListBloco(){

        #verifica o login
        if(yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        #atribui a tabela blocos na var
        $blocoTable = BlocoModel::tableName();
        #atribui a tabela condominios na var
        $condoTable = CondominioModel::tableName();

        #realiza a query de busca dos dados no BD
        $query = (new \yii\db\Query())
        ->select(
            'blo.id,
            condo.nomeCondo as condoBloco,
            blo.nomeBloco,
            blo.andares,
            blo.unidades,
            blo.dataCadastro'
        )
        ->from($blocoTable.' blo')
        #faz o inner join da tabela condominios para buscar a relacao
        ->innerJoin($condoTable.' condo','condo.id = blo.condoBloco');

        #paginacao com 6 itens
        $paginacao = new Pagination([
            'defaultPageSize' => 6,
            'totalCount' => $query->count(),
        ]);

        #ordena a lista de blocos pelo id
        $bloco = $query->orderBy('id')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();
        
        #renderiza a listagem
        return $this->render('list-bloco', [
            'blocos' => $bloco,
            'paginacao' => $paginacao,
        ]);
    }

    #funcao para renderizar o cadastro
    public function actionBloco(){

        #verifica o login
        if(yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        
        return $this->render('bloco');
    }

    #funcao para realizar o cadastro
    public function actionRealizaCadastroBloco(){
        $request = \yii::$app->request;

        #se request for post, atribui os dados na model e salva
        if($request->isPost){
            $model = new BlocoModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['bloco/list-bloco']);
        }

        return $this->render('bloco');
    }

    #funcao para listar os blocos em outros cadastros
    public static function listBlocoSelect(){
        $query = BlocoModel::find();
        return $query->orderBy('nomeBloco')->all();
    }

    #funcao para listar somente os blocos de determinado condominio em outros cadastros
    public static function listBlocoSelectEdit($from){
        $query = BlocoModel::find();
        
        #filtra somente os blocos do condominio selecionado
        $data = $query->where(['condoBloco' => $from])->orderBy('id')->all();
        return $data;
    }

    #API para listar somente os blocos de determinado condominio em outros cadastros
    public function actionListaBlocosApi(){
        $request = \yii::$app->request;
        $query = BlocoModel::find();
        
        #filtra somente os blocos do condominio selecionado
        $data = $query->where(['condoBloco' => $request->post()])->orderBy('id')->all();

        #junta os blocos num array e retorna em json
        $dados = array();
        $i = 0;
        foreach($data as $d){
            $dados[$i]['id'] = $d['id'];
            $dados[$i]['nomeBloco'] = $d['nomeBloco'];
            $i++;
        }

        return json_encode($dados);
    }

    #funcao abrir a edicao do bloco
    public function actionEditaBloco(){
        #esconde o layout
        $this->layout = false;

        $request = \yii::$app->request;
        
        #se request for get, busca os blocos e filtra pelo id selecionado no get
        if($request->isGet){
            $query = BlocoModel::find();
            $blocos = $query->where(['id' => $request->get()])->one();
        }
        #renderiza a edicao
        return $this->render('edita-bloco',[
            'edit' => $blocos
        ]);
    }

    #funcao para salvar os dados editados
    public function actionEditaCadastroBloco(){

        $request = \yii::$app->request;

        #se request for post, busca o bloco pelo id, e coloca os dados do post na model
        if($request->isPost){

            $model = BlocoModel::findOne($request->post('id'));
            $model->attributes = $request->post();

            #se os dados conferem com o BD, atualiza os dados
            if($model->update()){
                return $this->redirect(['bloco/list-bloco']);
            }
            #se nao, exiba erro
            else{
                return $this->redirect(['bloco/list-bloco', 'msg' => 'erro']);
            }
        }
    }

    #funcao para deletar bloco
    public function actionDeletaBloco(){
        $request = \yii::$app->request;

        #se request for get, pega o id do bloco no get
        if($request->isGet){
            $model = BlocoModel::findOne($request->get('id'));

            #se pegou o id, deleta o bloco
            if($model->delete()){
                return $this->redirect(['bloco/list-bloco', 'myAlert' => ['type' => 'success', 'msg' => 'Registro deletado']]);
            }
            #se nao, exiba erro
            else{
                return $this->redirect(['bloco/list-bloco', 'myAlert' => ['type' => 'danger', 'msg' => 'Registro não deletado']]);
            }
        }
    }
}
?>

controllers/PetController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\PetModel;
use app\components\alertComponent;
use app\models\MoradorModel;
use Yii;

class PetController extends Controller{
    #funcao para listar pets
    public function actionListPet(){
        #verifica se o usuario está logado
        if(yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        #atribui a tabela pets na var
        $petTable = PetModel::tableName();

        #atribui a tabela morador na var
        $morTable = MoradorModel::tableName();

        #busca os pets no BD
        $query = (new \yii\db\Query())
        ->select(
            'pet.id,
            mor.nome as from_morador,
            pet.nomePet,
            pet.tipo,
            pet.dataCadastro
            '
        )
        ->from($petTable.' pet')
        #faz o inner join da tabela moradores para buscar a relacao
        ->innerJoin($morTable.' mor','mor.id = pet.from_morador');

        #paginacao com 6 itens
        $paginacao = new Pagination([
            'defaultPageSize' => 6,
            'totalCount' => $query->count(),
        ]);

        #ordena a lista pelo id
        $pet = $query->orderBy('id')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();
        
        #renderiza a listagem
        return $this->render('list-pet', [
            'pets' => $pet,
            'paginacao' => $paginacao,
        ]);
    }

    #funcao para renderizar o cadastro de pet
    public function actionPet(){

        #verifica se está logado
        if(yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        
        return $this->render('pet');
    }

    public function actionRealizaCadastroPet(){
        $request = \yii::$app->request;

        #se request for post, busca os atributos da model e salva os dados
        if($request->isPost){
            $model = new PetModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['pet/list-pet']);
        }

        return $this->render('pet');
    }

    #funcao para abrir a edicao de pet
    public function actionEditaPet(){
        #esconde o layout da edicao
        $this->layout = false;

        $request = \yii::$app->request;

        #se request for get, busca os pets e filtra pelo id selecionado no get
        if($request->isGet){
            $query = PetModel::find();
            $pets = $query->where(['id' => $request->get()])->one();
        }
        #renderiza a tela de edicao do pet
        return $this->render('edita-pet',[
            'edit' => $pets
        ]);
    }

    #funcao para salvar os dados editados do pet
    public function actionEditaCadastroPet(){

        $request = \yii::$app->request;

        #se request for post, busca um pet pelo id, e coloca os atributos do request na model
        if($request->isPost){

            $model = PetModel::findOne($request->post('id'));
            $model->attributes = $request->post();

            #se os dados baterem com as tabelas do BD, atualiza o pet e redireciona para a listagem
            if($model->update()){
                return $this->redirect(['pet/list-pet']);
            }
            #se nao, exiba erro
            else{
                return $this->redirect(['pet/list-pet', 'msg' => 'erro']);
            }
        }
    }

    #funcao para deletar o pet
    public function actionDeletaPet(){
        $request = \yii::$app->request;

        #se request for get, pega o id do pet no get
        if($request->isGet){
            $model = PetModel::findOne($request->get('id'));

            #se pegou o id, deleta o pet
            if($model->delete()){
                return $this->redirect(['pet/list-pet', 'myAlert' => ['type' => 'success', 'msg' => 'Registro deletado']]);
            }
            #se nao, exiba erro
            else{
                return $this->redirect(['pet/list-pet', 'myAlert' => ['type' => 'danger', 'msg' => 'Registro não deletado']]);
            }
        }
    }
}
?>

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use kartik\icons\FontAwesomeAsset;

FontAwesomeAsset::register($this);

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="icofont/icofont.min.css">
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => '<img src="img/building-alt.svg" width="80px"/>',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
            [
                'label' => 'Início',
                'url' => Yii::$app->homeUrl
            ],
            [
                'label' => 'Administroras',
                'items' => [
                    [
                        'label' => 'Listar', 
                        'url' => ['adm/list-admin']
                    ],
                    [
                        'label' => 'Cadastrar',
                        'url' => ['adm/admin']
                    ]
                ],
            ],
            [
                'label' => 'Condomínios',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['condo/list-condominio']
                    ],
                    [
                        'label' => 'Cadastrar',
                        'url' => ['condo/condominio']
                    ]
                ]

            ],
            [
                'label' => 'Blocos',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['bloco/list-bloco']
                    ],
                    [
                        'label' => 'Cadastrar',
                        'url' => ['bloco/bloco']
                    ]
                ]

            ],
            [
                'label' => 'Unidades',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['unidade/list-unidade']
                    ],
                    [
                        'label' => 'Cadastrar',
                        'url' => ['unidade/unidade']
                    ]
                ]

            ],
            [
                'label' => 'Moradores',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['morador/clientes']
                    ],
                    [
                        'label' => 'Cadastrar',
                        'url' => ['morador/cadastro']
                    ]
                ]

            ],
            [
                'label' => 'Conselhos',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['conselho/list-sindico']
                    ],
                    [
                        'label' => 'Cadastrar',
                        'url' => ['conselho/sindico']
                    ]
                ]
            ],
            [
                'label' => 'Pets',
                'items' => [
                    [
                        'label' => 'Listar',
                        'url' => ['pet/list-pet']
                    ],
                    [
                        'label' => 'Cadastrar',
                        'url' => ['pet/pet']
                    ]
                ]
            ],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'form-inline'])
                . Html::submitButton(
                    'Logout (' .Yii::$app->user->identity->usuario . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0 mt-5">
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer>
        <div class="info">
            <span>&copy; Todos os direitos reservados.</span> 
        </div>

        <div class="support">
            <a href="#">(47) 90123-4567</a> 
        </div>

        <div class="version float-right">
            <small class="versionControl">v 1.0</small>
        </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>