controllers/PetController.php
<?
namespace app\controllers;

use yii\web\Controller;
use yii\data\Pagination;
use app\models\PetModel;
use app\components\alertComponent;
use app\models\MoradorModel;
use Yii;

class PetController extends Controller{
    #funcao para listar pets
    public function actionListPet(){
        #verifica se o usuario está logado
        if(yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }

        #atribui a tabela pets na var
        $petTable = PetModel::tableName();

        #atribui a tabela morador na var
        $morTable = MoradorModel::tableName();

        #busca os pets no BD
        $query = (new \yii\db\Query())
        ->select(
            'pet.id,
            mor.nome as from_morador,
            pet.nomePet,
            pet.tipo,
            pet.dataCadastro
            '
        )
        ->from($petTable.' pet')
        #faz o inner join da tabela moradores para buscar a relacao
        ->innerJoin($morTable.' mor','mor.id = pet.from_morador');

        #paginacao com 6 itens
        $paginacao = new Pagination([
            'defaultPageSize' => 6,
            'totalCount' => $query->count(),
        ]);

        #ordena a lista pelo id
        $pet = $query->orderBy('id')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();
        
        #renderiza a listagem
        return $this->render('list-pet', [
            'pets' => $pet,
            'paginacao' => $paginacao,
        ]);
    }

    #funcao para renderizar o cadastro de pet
    public function actionPet(){

        #verifica se está logado
        if(yii::$app->user->isGuest){
            return $this->redirect(['site/login']);
        }
        
        return $this->render('pet');
    }

    public function actionRealizaCadastroPet(){
        $request = \yii::$app->request;

        #se request for post, busca os atributos da model e salva os dados
        if($request->isPost){
            $model = new PetModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['pet/list-pet']);
        }

        return $this->render('pet');
    }

    #funcao para abrir a edicao de pet
    public function actionEditaPet(){
        #esconde o layout da edicao
        $this->layout = false;

        $request = \yii::$app->request;

        #se request for get, busca os pets e filtra pelo id selecionado no get
        if($request->isGet){
            $query = PetModel::find();
            $pets = $query->where(['id' => $request->get()])->one();
        }
        #renderiza a tela de edicao do pet
        return $this->render('edita-pet',[
            'edit' => $pets
        ]);
    }

    #funcao para salvar os dados editados do pet
    public function actionEditaCadastroPet(){

        $request = \yii::$app->request;

        #se request for post, busca um pet pelo id, e coloca os atributos do request na model
        if($request->isPost){

            $model = PetModel::findOne($request->post('id'));
            $model->attributes = $request->post();

            #se os dados baterem com as tabelas do BD, atualiza o pet e redireciona para a listagem
            if($model->update()){
                return $this->redirect(['pet/list-pet']);
            }
            #se nao, exiba erro
            else{
                return $this->redirect(['pet/list-pet', 'msg' => 'erro']);
            }
        }
    }

    #funcao para deletar o pet
    public function actionDeletaPet(){
        $request = \yii::$app->request;

        #se request for get, pega o id do pet no get
        if($request->isGet){
            $model = PetModel::findOne($request->get('id'));

            #se pegou o id, deleta o pet
            if($model->delete()){
                return $this->redirect(['pet/list-pet', 'myAlert' => ['type' => 'success', 'msg' => 'Registro deletado']]);
            }
            #se nao, exiba erro
            else{
                return $this->redirect(['pet/list-pet', 'myAlert' => ['type' => 'danger', 'msg' => 'Registro não deletado']]);
            }
        }
    }
}
?>

views/pet/edita-pet.php
<?

use app\components\selectedComponent;
use yii\helpers\Url;
use app\controllers\MoradorController;
use app\components\animaisComponent;
?>

<center class="mt-4 pb-4">
    <h1 class="col-12">Edição de Pet</h1>
</center>
    <form action="<?echo Url::to(['pet/edita-cadastro-pet']);?>" method="POST" class="formPet">
        <div class="row">
            <div class="col-12 col-md-4 mb-3">
                <select name="from_morador" class="custom-select" required>
                    <option value="">Selecione o(a) dono(a)...</option>
                    <?
                    foreach(MoradorController::listMoradorSelect() as $mor){
                    ?>
                    <option value="<?=$mor['id']?>"<?=selectedComponent::isSelected($mor['id'], $edit['from_morador'])?>><?=$mor['nome']?></option>
                    <?}?>
                </select>
            </div>
            <div class="col-12 col-md-4 mb-3">
                <input type="text" class="form-control" name="nomePet" value="<?=$edit['nomePet']?>" required placeholder="Nome">
            </div>
            <div class="col-12 col-md-4 mb-3">
                <select name="tipo" class="custom-select" required>
                    <option value="">Selecione o tipo do animal...</option>
                    <?
                    foreach(animaisComponent::animais() as $val=>$nome){
                    ?>
                    <option value="<?=$val?>"<?=selectedComponent::isSelected($val, $edit['tipo'])?>><?=$nome?></option>
                    <?}?>
                </select>
            </div>
            
            <input type="hidden" name="<?= \yii::$app->request->csrfParam;?>" value="<?= \yii::$app->request->csrfToken;?>">

            <input type="hidden" name="id" value="<?=$edit['id']?>">

            <div class="col-12 col-md-12 mt-3">
                <center>
                    <button class="btn btn-info col-6 mb-2" type="submit">Salvar</button>
                </center>
            </div>
        </div>
    </form>

views/pet/list-pet.php
<?

use app\components\modalComponent;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\Url;
use app\components\alertComponent;

$url_site = Url::base(true);

if(isset($_GET['myAlert'])){
    echo alertComponent::myAlert($_GET['myAlert']['type'],$_GET['myAlert']['msg']);
}

?>

<center>
<h1>Pets</h1>
</center>
<div class="row">
    <div class="col-12">
        <div class="table-responsive">
            <table class="table mt-3" id="listaPets">
                <thead class="thead-dark">
                    <tr>
                    <th scope="col">Dono(a)</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Tipo de Animal</th>
                    <th scope="col">DT. Cadastro</th>
                    <th align="center"><a href="index.php?r=pet%2Fpet" class="btn btn-info btn-sm">ADICIONAR</a></th>
                    </tr>
                </thead>
                <tbody>
                    <? 

                    foreach($pets as $dados){
                        
                    ?>
                    <tr data-id="<?=$dados['id']?>">
                    <td><?=$dados['from_morador']?></td>
                    <td><?=$dados['nomePet']?></td>
                    <td><?=$dados['tipo']?></td>
                    <td><?=Yii::$app->formatter->format($dados['dataCadastro'],'date')?></td>
                    <td>
                        <a style="padding-right: 25px;" href="<?=$url_site?>/index.php?r=pet/deleta-pet&id=<?=$dados['id']?>" class="removerPet"><i class="icofont-ui-delete botao"></i></a>
                        <a class="openModal" href="<?=$url_site?>/index.php?r=pet/edita-pet&id=<?=$dados['id']?>"><i class="icofont-edit botao"></i></a>
                    </td>
                    </tr>
                    <?}?>
                    <tr>
                    <td colspan="3">&nbsp;</td>
                    <td colspan="2" align="right" class="totalRegistros">Total Registros: <?=$paginacao->totalCount?></td>
                    </tr>
                </tbody>
            </table>
        </div>    
    </div>
</div>
<div class="row">
    <?= LinkPager::widget(
        [
            'pagination' => $paginacao,
            'linkContainerOptions' => [
                'class' => 'page-item'
            ],
            'linkOptions' => [
                'class' => 'page-link'
            ],
            'disabledListItemSubTagOptions' => [
                'class' => 'page-link'
            ]
        ]
    ) ?>
</div>
<?=modalComponent::initModal();?>

views/pet/pet.php
<?

use app\components\animaisComponent;
use yii\helpers\Url;
use app\controllers\MoradorController;
?>

<center class="mt-4 pb-4">
    <h1 class="col-12">Cadastro de Pet</h1>
</center>
    <form action="<?echo Url::to(['pet/realiza-cadastro-pet']);?>" method="POST" class="formPet">
        <div class="row">
            <div class="col-12 col-md-4 mb-3">
                <select name="from_morador" class="custom-select" required>
                    <option value="">Selecione o morador...</option>
                    <?
                    foreach(MoradorController::listMoradorSelect() as $mor){
                    ?>
                    <option value="<?=$mor['id']?>"><?=$mor['nome']?></option>
                    <?}?>
                </select>
            </div>
            <div class="col-12 col-md-4 mb-3">
                <input type="text" class="form-control" name="nomePet" value="" required placeholder="Nome">
            </div>
            <div class="col-12 col-md-4 mb-3">
                <select name="tipo" class="custom-select" required>
                    <option value="">Selecione o tipo de animal...</option>
                    <?
                    foreach(animaisComponent::animais() as $val=>$nome){
                    ?>
                    <option value="<?=$val?>"><?=$nome?></option>
                    <?}?>
                </select>
            </div>
            
            <input type="hidden" name="<?= \yii::$app->request->csrfParam;?>" value="<?= \yii::$app->request->csrfToken;?>">

            <div class="col-12 col-md-12 mt-3">
                <center>
                    <button class="btn btn-info col-6" type="submit">Enviar</button>
                </center>
            </div>
        </div>
    </form>